jms_security_extra:
    secure_all_services: false
    expressions: true
    
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_VENDOR:      ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_VENDOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user2d: { password: user2d, roles: [ 'ROLE_USER' ] }
                    user3d: { password: user3d, roles: [ 'ROLE_USER' ] }
                    seek: { password: seek, roles: [ 'ROLE_VENDOR' ] }
                    atlas: { password: driveway, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        static:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:  ^/
            security: true
            form_login:
                check_path: /login_check
                login_path: /login
                use_referer: true
            logout:
                path:   /logout
                target: /login
            #anonymous: ~
            #http_basic: 
            #    realm: "Secured Atlas Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/gallery, roles: ROLE_USER }
        - { path: ^/gallery/v/seek, roles: ROLE_VENDOR }
        - { path: ^/, roles: ROLE_ADMIN }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
