parameters:
#    atlas_gallery.example.class: Atlas\GalleryBundle\Example

services:
#    atlas_gallery.example:
#        class: %atlas_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
